// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7m-hsz24rW6EM8JFc4rdQDugk5eP2zqw',
    appId: '1:862604032533:web:8e86994de9224fe0e96c1c',
    messagingSenderId: '862604032533',
    projectId: 'roads-3moods',
    authDomain: 'roads-3moods.firebaseapp.com',
    storageBucket: 'roads-3moods.firebasestorage.app',
    measurementId: 'G-RKZ1DFF6Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD5H5eNKOGg-qov85FFTEbEfiQ--nzeFo',
    appId: '1:862604032533:android:85caa4bb464293aee96c1c',
    messagingSenderId: '862604032533',
    projectId: 'roads-3moods',
    storageBucket: 'roads-3moods.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfaCZ4mvJhnBxdm4jhQZ2WdyTdBWYQMhY',
    appId: '1:862604032533:ios:82fe178b27b1041ae96c1c',
    messagingSenderId: '862604032533',
    projectId: 'roads-3moods',
    storageBucket: 'roads-3moods.firebasestorage.app',
    iosBundleId: 'com.example.threeRoadsThreeMoods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfaCZ4mvJhnBxdm4jhQZ2WdyTdBWYQMhY',
    appId: '1:862604032533:ios:82fe178b27b1041ae96c1c',
    messagingSenderId: '862604032533',
    projectId: 'roads-3moods',
    storageBucket: 'roads-3moods.firebasestorage.app',
    iosBundleId: 'com.example.threeRoadsThreeMoods',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7m-hsz24rW6EM8JFc4rdQDugk5eP2zqw',
    appId: '1:862604032533:web:62e8161ad2c5eb50e96c1c',
    messagingSenderId: '862604032533',
    projectId: 'roads-3moods',
    authDomain: 'roads-3moods.firebaseapp.com',
    storageBucket: 'roads-3moods.firebasestorage.app',
    measurementId: 'G-5XKF4C9C59',
  );
}
